### PR TITLE
added optional QT5 support - LedDevicePhilipsHue needs proper fixes

### PR DESCRIPTION
**Pull request by frostworx**
hi!
after years I recently switched from (mighty) boblight to hyperion.
my (~amd64 gentoo) system is qt5 only, so I created this QT5 fork, which might be of some use.
options I use for a successful build are
"cmake .. -DENABLE_QT5=On -DENABLE_DISPMANX=Off"
QHttp was removed/replaced in qt5 and as I don't have PhilipsHue
LedDevicePhilipsHue needs a proper fix from someone else :)

### CODE REVIEW

**Comment by ntim** [comment]
I will look into it. Turns out there is a compatibility addon which maintains the functionality of QtHttp. Nevertheless, it is recommended to switch to QNetworkAccessManager.

**Comment by ntim** [comment]
I have implemented the requests with QNetworkAccessManager: 6e65da9338d131d1017051e505db8c28696adf4f
But I can not test it until next weekend.

**Comment by frostworx** [comment]
sounds good :)

**Comment by Kwiboo** [comment]
There should be no need to use all this `#ifdef ENABLE_QT5` in the code, Qt4.8 also supports `toLatin1/fromLatin1` and `QNetworkAccessManager`
In [my old Qt5 fork](https://github.com/Kwiboo/hyperion/commits/qt5) I even replaced `FindQt4.cmake` with the cmake builtin version (cmake 2.8.11+) and does compile time check for both Qt5 and Qt4

`hyperion` compiled and worked fine using either the [Qt4 or Qt5 package](https://github.com/Kwiboo/OpenELEC.tv/commits/openelec-hyperion) under the OpenELEC build system when I updated the hyperion package in RasPlex

For RasPlex we ended up using Qt4 since it generated a smaller footprint in the image

**Pull request merged**
