### PR TITLE
 End Frame fixed (Issue #361)

### PR DESCRIPTION
**Pull request by AEtHeLsYn**
End frame fixed using info from https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/

### CODE REVIEW

**Comment by pcaffardi** [comment]
I tested last hyperion and same issue again: last led is wrong. This is my patch (source included: please merge it): http://www.arsenio.net/download/hyperion_apa102_patch.zip

**Comment by zebrapants** [comment]
I just tried the latest rpi binary (https://github.com/tvdzwan/hyperion/blob/master/deploy/hyperion_rpi.tar.gz - md5sum of hyperiond is 7e742050b13b493723e6a698c00381f5) and it does not solve the problem. The patched binary provided by @pcaffardi works correctly. I have 192 leds.

**Comment by AEtHeLsYn** [comment]
Last version works correctly but @tvdzwan has to update binaries with last version.

**Comment by RickDB** [comment]
@pcaffardi Thanks for the fix!
Any chance the APA102 patch can be merged?

**Comment by RickDB** [comment]
@pcaffardi Thanks for the fix!
@tvdzwan Any idea if this patch will make it into the next binary release?

**Pull request merged**
