### PR TITLE
Add UDP protocol support

### PR DESCRIPTION
**Pull request by penfold42**
This adds UDP protocol support to hyperion.

It is designed to fire UDP packets at something like an ESP8266 arduino based WiFi receiver.

### CODE REVIEW

**Comment by jebos** [comment]
looking forward to this, would be great to have some documentation about this.

**Comment by penfold42** [comment]
I've added some (very) basic documentation on the protocol and also added an "effect" than can listen to UDP packets.
Now Hyperion can both send and receive UDP led data !

**Comment by penfold42** [comment]
This pull request should help #443 #404 #329

**Comment by Gamadril** [comment]
I would not call it a "device", because UDP is a protocol on the transport layer, but you also specifiy the data protocol for LED data here. There are also ther device which also use UDP for communication, but have different data formats. TPM2.NET for example. I would suggest to make it a base class and derive from it for your device implementation. I did it that way in the hyperion-poco branch.

**Comment by jebos** [comment]
Works for me like a charm. I used a v4l2loopback device and have two hyperion instances grabbing the video signal on a raspberry pi2. the one controlls a ldpd8806 LED Stribe which is directly connected to the raspberry pi2. The second hyperion send its data to network and get received by a second raspberry running for it self an hyperion.

receiver is a simple pyhton server/effect:

```
import socket
import pickle
 
UDP_IP = ""
UDP_PORT = 8888

sock = socket.socket(socket.AF_INET, # Internet
                                  socket.SOCK_DGRAM) # UDP
sock.bind((UDP_IP, UDP_PORT))

while True:
  srgb = bytearray(4096)
  number,addr = sock.recvfrom_into(srgb) # buffer size is 
     
  ledDataServer = bytearray()
  for i in range(1, number-3, 3):
    ledDataServer += bytearray((srgb[i+1], srgb[i],srgb[i+2]))

  hyperion.setColor(ledDataServer)
	  
  # wait 100ms
  time.sleep(0.1)

```
this expects that the client send its data in protocol 1 and on port 8888

**Comment by penfold42** [comment]
Great ! My first customer so far.

Did you see the UDP lists see effect I also committed ?

I'm considering a rewrite to implement a UDP base class separate from the protocol stuff and tidy it up a bit more.

This won't happen for a while tho - should we look to get this merged in the meantime ?

**Comment by penfold42** [comment]
@tvdzwan - dont like my PR ?

**Comment by NicoHood** [comment]
You have to resolve the merge conflicts first.

**Comment by penfold42** [comment]
I don't know what I'm doing with github so this will take a while.
It didn't have any conflicts when I first created the pull request.
Is it the subsequent now merged pull requests that now cause this ?

**Comment by NicoHood** [comment]
Yes.
You need to add the remote upstream git `git add remote upstream gitlinkofhyperionmain`. Then do `git fetch upstream` and `git merge upstream/master`. It will tell you which file conflicts, and they will have a marker inside. Fix it. Then do `git add filename` and then do `git commit` and `git push` again.

**Comment by penfold42** [comment]
Thanks !

**Comment by redPanther** [comment]
I've looked into the merge conflict and I found out that our commits collide a bit - but nothing serious ;-)

here the steps to resolve the issue:

like NicoHood said in your clone of hyperion:
```
git remote add upstream https://github.com/tvdzwan/hyperion.git 
git fetch upstream
git merge upstream/master
```
then 2 files have a conflict.
edit those files:
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/CMakeLists.txt

remove git markers: <<<<<<< ======= >>>>>>>
(or in other words: keep all code lines - yours and upstream )
(make a test compile)
add, commit and push your changes.

**Comment by planschmuh** [comment]
@penfold42 - I like your udp solution. Is it possible to send the upd packets to multiple receivers?
 e.g. "output"     : "receiver1:2391;receiver2:2391", "protocol" : 0, .. 

 If not, maybe you can implement this feature?

**Comment by penfold42** [comment]
Not yet, but it shouldn't be hard to add.

Maybe multicast would be a better option ? That way only 1 packet is sent and the receivers would all see it.
That might automagically work already. I'll test it.

**Comment by planschmuh** [comment]
Oh shame on me, I did not thought about it.. Multicast works like a charm! Thanks :)

**Pull request merged**
