### PR TITLE
make priority of boot effect adjustable.

### PR DESCRIPTION
**Pull request by redPanther**
When boot effect is set to "stay forever" (duration 0), no effect can't be set afterwards.
Now it is settable in config and everybody can set the value to something that fits the needs.

this PR should fullfill @solidewebservices issue in issue #437 and is usefull for issue #77 too

### CODE REVIEW

**Comment by penfold42** [comment]
This is excellent - I needed it today whilst testing my new ws2801 to ws2812 converter

**Comment by redPanther** [comment]
to full fill issue #77 I added abilty to set static color on boot. for more details look into config/hyperion.config "bootsequence"

@penfold42 thx for liking my patch :-)

**Comment by pigbait** [comment]
so how do i make the static color? will it be somthing like

// 	"bootsequence" : 
// 	{
// 		"effect" : "pink",
// 		"duration_ms" : 0
// 	},

**Comment by NicoHood** [comment]
Do you have utf8 errors in the PR? A lot of lines are marked red. Also I'd remove some of the tabs, so lines you did not really change are marked so. This makes the patch a lot more clear.

**Comment by redPanther** [comment]
@pigbait 
```
	"bootsequence" : 
	{
		"color"       : [200,100,160],
		"effect"      : "Rainbow swirl fast",
		"duration_ms" : 3000,
		"priority"    : 0
	},
```
color is a rgb value. Do not set duration to 0, then you will see your effect instead of color.

@NicoHood 
thx for your feedback, but here on github and on my computer it looks fine, can you give me a hint?

**Comment by pigbait** [comment]
@redPanther 

thanks for the setup but doesn't seem to set it. stays at the rainbow swirl

**Comment by redPanther** [comment]
did you set the duration to   "duration_ms" to 0 as I can see in your prior post. Did you use my config example?
Please use my example config as shown above. There you should see the swirl for 3 seconds then a pink color.

**Comment by brindosch** [comment]
@redPanther 
I am extend HyperCon with the latest features and additions at the moment .
I struggle with your implementation of static color.
Due to the point that this is not "streamlined" with the Hypercon .conf formatting.

I would really appreciate a second pull request with a adjusted config

I prepared everything for the following formatting (doesn´t matter how you call it, just split R/G/B)

`	"bootsequence" : 
	{
		"colorR" : 0,
		"colorB" : 0,
		"colorG" : 0,
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 3000,
		"priority" : 0
	},`

Thank you in advance

brindosch

**Comment by redPanther** [comment]
hmm I'm not favor this, because my implemention is the way all effects implemented color settings.
e.g. https://github.com/tvdzwan/hyperion/blob/master/effects/knight-rider.json
If you dislike the [r,g,b] we can use html color "#rrggbb" but it is unnessecary complex for both sides (implementing and usage)

If we do so as you suggest, all effects should be altered to make it consistent.

**Comment by brindosch** [comment]
uff this is sad. As i could say
if i put strings in the output, i will get this
"0,0,0" (if i merge the values) But then have to check how to trigger the merge for new values

**Comment by brindosch** [comment]
So the solution is a workaround or we convert everything in den effects.

Maybe it´s better to convert everything. 

Yes, people will cry cause effects won´t work, until every image get´s an update.

**Comment by redPanther** [comment]
Things in [] aren't strings. This is an json array. Perhaps put as string is wrong. Put as array would be solve the issue.

The led config is also a json array.

**Comment by brindosch** [comment]
This is a good hint, will have a look to the JsonStringBuffer

**Comment by brindosch** [comment]
This was to easy
Added a new value "AddArray" to JsonStringBuffer. Now i could easy request this :+1: 

`		"bootsequence" : `
`		{`
`			"color" : [0,0,0],`
`			"effect" : "Rainbow swirl fast",`
`			"duration_ms" : 3000,`
`			"priority" : 0`
`		},`

**Comment by brindosch** [comment]
unbenannt
And DONE. Just modified it to accept three int values in a row. Well very good solution.
big thank you for the hint. sometimes the solution is too near.

**Comment by pigbait** [comment]
wow awesome work guys, very nice seeing you two figure out a proper solution

**Comment by brindosch** [comment]
@pigbait 
If you want to play around, this version is online
(some messags above)

**Comment by pigbait** [comment]
@brindosch

I will play around with it tonight.

**Comment by redPanther** [comment]
@brindosch I think it is a good idea to add a hint that 0ms duration means infinity. 

I think this can lead to missunderstandings when somebody want to switch off the effect (set to 0) and than the swirl stays for ever.

The priority should be 990 as default. This prevents unexpected behaviour in combination with duration 0.

**Comment by brindosch** [comment]
I added the hint in the config file itself, until i implemented a good solution for "help files/frames"
I will set it to 990,
thank you and very good work!

There is just found one thing with the BootEffect Engine that is strange.
It is not possible to use newer effects like "police lights single"
Are they hardcoded? Is it possible to change this to "check which effects are loaded and then use them if requested from the .conf."
If the requested effect is not present, nothing happend.

Could you investigate this?

**Comment by redPanther** [comment]
Effects aren't hardcoded. This is the same mechanism that is used by json server when effects send via remote.
Important is, that the effect name is taken from inside the json file. Perhaps it's case sensitive.
I use my cinema effects (my master branch contain my new effects) and it worked very well.

**Comment by brindosch** [comment]
> from inside the json file

I never thought about this. Are you sure you don´t want to set the first steps for hyperion splittting in "core" and "extension-devices-etc" plugin/load on demand system?

There are people who are willing to help you ;)
I could integrate the on off switches in hypercon *laugh*

Thank you

**Comment by pigbait** [comment]
@brindosch 

this is my hyperion.config.json setting using your new hyperion config, for some reason I get static blue for a quick second and then rainbow swirl. not sure if i have something set wrong?
`"bootsequence" : 
	{
		"color" : [0,38,255],
		"effect" : "None",
		"duration_ms" : 3300,
		"priority" : 990
	},
`

**Comment by redPanther** [comment]
If you didn't want an effect then delete the line or set it to ""'
The effect must contain a valid effect name or nothing. Valid effect names are inside all <effect>.json files (the name field)

The color is set before effect is started, thats why you see blue before the rainbow.

**Comment by brindosch** [comment]
the rainbow swirl?
I tested these with effect "none" so there is no "none" effect nothing should happen? you should get 3 seconds blank and then the color?

**Comment by pigbait** [comment]
hmm I've tried with even a different effect and its still rainbow swril

**Comment by pigbait** [comment]
hmm I've tried with even a different effect and its still rainbow swril,

**Comment by redPanther** [comment]
There must be another problem. There is no default effect. When effect is not loadable (wrong name/effect error) then nothing is shown. Perhaps you edit the wrong config or did you double define the bootsequence?

Start hyperion with your config directly from commandline and then you see the output.

**Comment by pigbait** [comment]
Ok i found the problem, I was replacing the hyperion.config.json file located in /ect directory. i just noticed its now located in /opt/hyperion/config so I sent my config there and it works awesome

**Comment by pigbait** [comment]
sorry to did something OLD but can can boot effects no longer be setup as static, my old settings would allow for an effect to stay on forever. not i cant seem to set that up?

**Pull request merged**
