### PR TITLE
Revert "Update LedDeviceAPA102.cpp by pcaffardi"

### PR DESCRIPTION
**Pull request by wisc17**
Reverts tvdzwan/hyperion#484

was working before so this merge was not needed
sorry for the inconvenience

### CODE REVIEW

**Comment by brindosch** [comment]
Thank you, indeed it reintroduced the EndFrame Bug
Compiled a new verion without it. Great!

**Comment by AEtHeLsYn** [comment]
Be careful guys, check the source code before commiting a change. Let's hope @tvdzwan merge the commit soon

**Comment by RickDB** [comment]
Build it against latest master branch with these changes however not getting the end frame bug like with the latest official binary.

**Comment by wisc17** [comment]
ok .. thats kind of weird since the last update of binarys was 28 days ago (jan 2016)
and the revert restores the APA102.cpp back to the last commit on Nov 4, 2015
... any ideas whats going wrong with the binarys?

**Comment by RickDB** [comment]
Yeah thought that official binary would have the fix already, went thru the commit log and couldn't find any mention of recent APA102 end frame fixes (after jan 2016 release) so didn't look like it was merged.

Other users ran into the APA102 end frame issue on the Mediaportal forums (Ambient area) so went from there, they had to use the previously patched binary posted by pcaffardi to make it work.
Upgraded tot APA102 2 weeks ago and used the wiki installation manual for Raspbian where after I ran into the last led issue as well, only fix that works at the moment is compiling from master branch or the old patched one.

**Comment by wisc17** [comment]
ok but this reverts back to november 2015 and you confirmed it working (#480) .. so it should be in the binarys since a long time *confused*
did @tvdzwan get something wrong while compiling ???

**Comment by RickDB** [comment]
Correct also with the master branch from 6 days it worked as expected.
Not sure why there would be a difference compared to binary release :(

Already double checked the number of leds with Arduino because if you input those incorrectly (more than available) you won't notice the end frame bug.

**Comment by wisc17** [comment]
ok i found it ..
following your text - install as described in wiki
i checked the install script - it will download hyperion.tar.gz - which is - hold on - 11 MONTHS old
instead it should maybe point to hyperion_rpi.tar.gz which is 28 days - almost up to date
i will add a pull request to fix that in a minute :p

**Comment by RickDB** [comment]
Awesome, thanks :+1:

**Comment by brindosch** [comment]
@wisc17 
Don´t invest that much time in it. I wrote a new Install/update script. Currently i test it with the users from the german raspberrypi forum.

**Comment by wisc17** [comment]
ok you do that ^^ but this is only a "typo" problem - we should correct this first before moving to the next level ;)

**Comment by brindosch** [comment]
the install script points to the old release.
On which image would you point now from the 5 releases?

**Comment by wisc17** [comment]
it should point to the hyperion_rpi.tar.gz
tested and running on my RPI

**Comment by brindosch** [comment]
Yes, you could update, but if you change the install.sh people would install on new devices they have no gpio2spi (cause tar just overwrites and gipo2spi is indeed not deleted)

**Pull request merged**
