### PR TITLE
Add color adjustment to all RBG channels

### PR DESCRIPTION
**Pull request by AEtHeLsYn**
**1.Tell us something about your changes.**

With this piece of code we are able to define which combination of R, G and B channels are our TV Red, Green and Blue. 
This modification makes the 'color correction' modification useless, as we can modify the whitelevel within the 'color adjustment' config file. 
To achieve a perfect color matching between led strip and TV we should follow these steps:

1. Use a pure white (FFFFFF) image/video and take a look at your led strip. If the led strip color is a bit red, green or blue modify the max channel level until you get a perfect white

2. Use different grey (3F3F3F, 7F7F7F, BFBFBF...) images/videos and adjust gamma of each R,G,B colors. You should change gamma levels of each channel until you get a perfect grey on every step.

3. Once you get a perfect gamma level, you can adjust R, G, B channels. Use pure red, green and blue (FF0000, 00FF00, 0000FF) images/videos and play with channel adjustments until you achieve a perfect red, blue and green. For example, my perfect green (according to TV) is 20,255,15.

4. Increase Saturation and/or Luminance if you want.

After the four steps you should have achieved a perfect calibration of the led strip, matching your TV colors.

**2. If this changes affect the .conf file. Please provide the changed section.**

Inside "color", there is a new configuration block:

	"color" :
	{
	.
	.
	.
		"channelAdjustment" : 
		[
			{
				"id"   : "default",
				"leds" : "*",
				"pureRed" :
				{
					"redChannel"	: 255,
					"greenChannel"	: 0,
					"blueChannel"	: 0
				},
				"pureGreen" :
				{
					"redChannel"	: 0,
					"greenChannel"	: 255,
					"blueChannel"	: 0
				},
				"pureBlue" :
				{
					"redChannel"	: 0,
					"greenChannel"	: 0,
					"blueChannel"	: 255
				}			
			}		
		],	
	.
	.
	.	
	},

**3. Comments.**

This modification makes "color correction" step not needed at all, as we can use the main channel of each color to limit output. I mean, the "redChannel" of "pureRed" perform the same operation of the red channel correction value. To avoid performing the same operation twice, would be good to implement this mod to HyperCon and delete the colorCorrection from it.

### CODE REVIEW

**Comment by brindosch** [comment]
I said don´t hurry! *complainabouttohavenotimeforeverything*
Hehe, thank you! very very great addition even with hyperion-remote.
Do you know how long i need to extend HyperCon with this *grml*
But dreams come true!

**Comment by AEtHeLsYn** [comment]
As always, the addition is fully tested, even hyperion-remote (and yes, you can send also those values at the same time as transform/correction/temperature ones) ;)

**Comment by brindosch** [comment]
One point, cause this is a new, we push Hyperion to V1.02.0. The point is now, could you have a look on that index thing too (hyperion-remote)? tpmodding and i thought about to publish not too often new feature bumps (To prevent that people have to update every week or every x days)
So we could push all in one

**Comment by NicoHood** [comment]
It would be better to have more concrete commit names and not only the single file editions. Otherwise we end up with a very confusing git history.

**Comment by AEtHeLsYn** [comment]
@brindosch 
I'm sorry about that, but as hyperion-remote is not intended as a remote configuration tool, there are no current implementations of led index. In fact, you can only apply transforms/corrections/adjustments using the already loaded qualifiers, not new ones. We may think about creating some other JSON functions that allow not only giving a led index. but modifing everything. I'm not a JSON expert tho, I can take a look but I don't know what we should do here.

@NicoHood 
I was coding directly on github while I was at work, I don't have git there. I know is a bit messy, but I didn't want to redo all the code. You can always commit to your fork and commit back here while keeping my work as is ;)

**Comment by brindosch** [comment]
No problem! We could drop the idea and save it for later.
I will start modify HyperCon soon. 
@NicoHood 
there is a command to merge all single commits to one?

**Comment by NicoHood** [comment]
Sure there is (its called squash i think, never used it though). Developing with git would make the thing still better, since single commits make it more readable. So 1000 and also 1 is still a bit bad. But yeah I know, that sometimes you need to test etc and cannot invent the solution straight on. I'd make a single commit out of all those.

**Comment by brindosch** [comment]
@AEtHeLsYn 
I will remove the complete color correction part from hypercon
Could hyperion handle that as long as it is in hyperion code? If people mix up versions config<>hyperion
Maybe we should remove the code inside hyperion and hyperion-remote too. If it is now useless.
and it is new, new enough that we may kick it better now than later
Will people get an error if they use a new hyperion (without colorC code) and a old config (with colorC config)

Your way of setting up colors i never used.
One big appeal to you: You have knowledge about this, we not. Could you provide a proper wiki article that descibes how to setting up colors the right way? People very often request this but my knowledge is limited. You could add pictures with the grey values and a white picute too, if you want. 

1. Use your new commited settings with a white picture
2. Adjust Gamma with Gamma spinner 
3.Use your new commited settings with  grey pictures (?!)

4. When do we use temperature values and for what?
5. Blacklvl - Checked
6 Whitelvl - What do we do with this setting now? You already said it. But what should we suggest to do with this?
Should i remove it from the HyperCon Panel? (Just the Panel, not the configfile. As long as i don´t know if something breaks- have to check code but minor)

I would really appreciate a good wiki article that explains everything. ColorAdjustment is a big part of hyperion and we now lacks a little for information - at least for the public out there.

Thank you for feedback!

**Comment by tociek** [comment]
Guys, what would you say if I develop KODI plugin for color calibration? I think it would be more convenient to adjust the settings while looking at TV :)

If you think it's a good idea I will take care of that within few weeks.

**Comment by AEtHeLsYn** [comment]
Well, the way I adjust leds is by using color patterns on Kodi and sending hyperion-remote commands til I get a perfect match.
Using a Kodi plugin to do that would be easier ;)

**Comment by brindosch** [comment]
Yes, a kodi plugin is a good addition

**Comment by tociek** [comment]
Perfect. Who can help me understand (or when I can find information) how to communicate with hyperion? Shall I use json interface?

**Comment by AEtHeLsYn** [comment]
@brindosch 
Working on a wiki article atm. And now about unused settings... we could leave hyperion as-is at the moment to keep backwards compatibility, but after all the color adjustments I made we only need this configuration to achieve a perfect control of color:

	"color" :
	{
		"temperature" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"temperatureValues" :
				{
					"red"   : 255,
					"green" : 255,
					"blue"  : 255
				}
			}
		],
		"channelAdjustment" : 
		[
			{
				"id"   : "default",
				"leds" : "*",
				"pureRed" :
				{
					"redChannel"	: 255,
					"greenChannel"	: 0,
					"blueChannel"	: 0
				},
				"pureGreen" :
				{
					"redChannel"	: 0,
					"greenChannel"	: 255,
					"blueChannel"	: 0
				},
				"pureBlue" :
				{
					"redChannel"	: 0,
					"greenChannel"	: 0,
					"blueChannel"	: 255
				}			
			}		
		],		
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",				
				"hsl" :
				{
					"saturationGain" : 1.0000,
					"luminanceGain"  : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
				}
			}
		],
		"smoothing" :
		{
			"type"            : "linear",
			"time_ms"         : 200,
			"updateFrequency" : 20.0000,
			"updateDelay"     : 0
		}
	},

Note that there is not any blacklevel/whitelevel at the transform, nor a hsv part (only hsl). Color correction isn't there too.

@tociek 
hyperion-remote uses json interface to send values to hyperion. I'm not an expert using json, but it wasn't too difficult to create new messages. Take a look at source code of hyperion-remote (json cpp) and you will find what you need

**Comment by segelkma** [comment]
This is awesome! Thank you. You said you could keep cpu usage low, but will it work on Raspberry A without falling behind? (If not tested yet, I may can do it once HyperCon was updated)
I wouldn't have any problem upgrading to a new Raspberry though :P

**Comment by AEtHeLsYn** [comment]
@segelkma 
Don't worry, the cpu usage is the same as before, maybe a 0,5-1% more, no need to upgrade to a new raspberry ;) 

@brindosch 
Wiki page created, take a look .

**Comment by penfold42** [comment]
Great work on the code and the wiki!

Imagine if your wiki was built Ito a wizard in the iOS and android apps...

**Comment by AEtHeLsYn** [comment]
@penfold42 
That would be awesome... any volunteers?

**Comment by brindosch** [comment]
@AEtHeLsYn 
What a great article, to be honest. I never understood everything but now i does.

Regarding the Blacklvl, i use it to keep the lights always on (0,03, 0,03, 0,01) on "dark" scenes
Is there a another possibility to keep that "feature" if we kick blacklvl? Or scew that setting something other up?

Thank you for all efforts you invested! I translate it later to german, a recalibration with the new HyperCon is not avoidable!

**Comment by AEtHeLsYn** [comment]
@brindosch 
What you do with blacklvl is reduce dynamic range of leds, You can achieve the same using threshold, but without changing range. 

Let's say you have a R range from 0.0 to 1.0 (0 - 255). Applying blacklvl config what you are doing is adding some amount of color (0.03) to every value and they multiply everything back to keep color in range. 

If you use threshold instead, the only thing you are going to do is keep lower values than 0.03 zeroed, but you will not affect the color range.

**Comment by brindosch** [comment]
I feard it, i screw something up with this :+1:  Always bad if you don´t know what you do. I will test this and report back.
Thank you!

**Comment by tpmodding** [comment]
awesome work! I take my hat off to you!

**Comment by emc02** [comment]
sorry for OT, but how can I update my hyperion installation on openelec to test this new features

**Comment by brindosch** [comment]
Please be patient until we tested and hypercon is ready.

**Comment by penfold42** [comment]
Or compile from source

**Comment by brindosch** [comment]
HyperCon is as near as complete. We could start testing
/Merged to Beta branch

**Comment by NicoHood** [comment]
No Idea how you did this via webgui, but thats better now. Good :)
https://github.com/tvdzwan/hyperion/commit/8ab465e59834f12a21709a6f4546bd6808a2a495

**Pull request merged**
