### PR TITLE
add configuratble latch time for ws2801

### PR DESCRIPTION
**Pull request by penfold42**
I'm using an attiny85 as a ws2801 to ws2811 protocol converter.

the 500uSec latch time can be better spent driving more LEDs more quickly.
This adds latchtime as a configuration option and it defaults to 500,000 for backward compatibility.

### CODE REVIEW

**Comment by brindosch** [comment]
Could you please explain in short what the new latch timer does?

**Comment by penfold42** [comment]
When driving a real ws2801 led strip, you use the SPI bus to clock all the bits of colour data Ito it and then you have to wait 500uSec to indicate you have finished clocking data. The led strip will then actually use the data to update the LEDs.

If you are using my (soon to be uploaded) ws2801 to ws2812 converter, this waiting/dead time is unnecessarily long.

The ws2812 only needs about 5uS

This PR enables you to configure this delay time.

**Comment by brindosch** [comment]
So if you get no input from the config file you use value 500000 which are 500uSec?

**Comment by penfold42** [comment]
Yep - this 500000 is the original fixed value.

**Comment by brindosch** [comment]
I will add this to HyperCon. Now i know what this does and nothing is harmed :)
Thank you for explaining

Merged

**Comment by penfold42** [comment]
This should probably be considered an "advanced" option - if you don't know you need it, you don't need it !

Btw, Thanks for all you work helping clean up and follow up  !

**Comment by tpmodding** [comment]
Advanced+optinal. Is it optional, if not we will get many issues why the old config doesnt work!!! 

Von meinem iPhone gesendet

**Comment by brindosch** [comment]
overruled!
ok, i won´t integrate it :)

**Comment by penfold42** [comment]
Optional - I made sure you can omit it

**Pull request merged**
