### PR TITLE
updated reference to rpi_ws281x sub module

### PR DESCRIPTION
**Pull request by penfold42**
The submodule has been updated but we were still referencing an older version.
This update is needed for hardware detection on RPI3 as there are 2 model strings that need to be checked for

Reference a issue #546

### CODE REVIEW

**Comment by brindosch** [comment]
I merge it, we will see soon what happen

**Comment by penfold42** [comment]
It looks good to me - when i browse it now references the updated version

thanks!

**Comment by tpmodding** [comment]
@penfold42 
http://www116.zippyshare.com/v/pdW34DHG/file.html
could you test the new binaries please? thanks!

**Comment by brindosch** [comment]
@penfold42 
So we need a feedback for Pi2 and Pi3
And we talk about ws2812B support am i right?
I am very confused now xD

**Comment by penfold42** [comment]
quick test for now - yep starts fine, no errors.
i'll hook some leds up to a spare pi shortly and report back

**Comment by penfold42** [comment]
hmnm.... this seems to hang my RPi 1 running 4.4.3-1-osmc.
It hangs with both the ws2812b and ws281x drivers.
I'll try updating and then try some dtparam changes

**Comment by brindosch** [comment]
@penfold42 
Sort osmc out, if this is broken.
To verifiy use better Raspbian?

**Comment by penfold42** [comment]
I fixed the crashing - I had lirc_rpi also using gpio 18.

Now it just flashed crazy - it worked yesterday!

**Pull request merged**
