### PR TITLE
Blackborder Improved +

### PR DESCRIPTION
**Pull request by wisc17**
added bottom right to osd mode
i think this is the final commit if no more ideas or requests

### CODE REVIEW

**Comment by brindosch** [comment]
Thank you @wisc17  for this improvement. 
It would be very nice, if you could add this to HyperCon too!

**Comment by wisc17** [comment]
i had a look at hyperCon .. and i was lost :p

**Comment by Fabi1080** [comment]
I'm currently travelling. But at the end of April i might have a look in this.

**Comment by brindosch** [comment]
@Fabi1080 
Glad to hear from you.
Have a look at your HyperCon Thread at .forum-raspberrypi.de
I left a message with some ideas and bugs ;)
Thank you!

**Pull request merged**
