### PR TITLE
Add invert option for ws281x

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
This adds support for inverting the data line so you can use an inverting level shifter

**2.** If this changes affect the .conf file. Please provide the changed section
Adds invert = 1 to invert the data line.
Default if not present is to not invert so is backwards compatible
**3.** Reference a issue (optional)
Nope

### CODE REVIEW

**Comment by brindosch** [comment]
@penfold42 
you changed the led count to 256, is this a workaround that people from "leds":0 to "leds":256 don´t have to input a "leds":x value or is this still a problem and we need the correct count?

**Comment by penfold42** [comment]
Oops. - sorry, forgot about that bit !

This is probably a more useful default. It's behaviour is the same as before just with a useful default If you omit it.

**Comment by tpmodding** [comment]
when we first merge https://github.com/tvdzwan/hyperion/pull/559 , wouldnt this not end in a conlfict?

**Comment by brindosch** [comment]
Yes, both will end in a conflict. Both wants to add their new value to line 330 in devicefactory. There may be some more due to line switching in ws281x

**Comment by penfold42** [comment]
I've redone the changes - should be good to merge now.

**Pull request merged**
