### PR TITLE
Allow hyperion-remote to send correction and transform at the same time

### PR DESCRIPTION
**Pull request by AEtHeLsYn**
@brindosch 
Here is the modification of hyperion-remote. I didn't changed a lot, only allowed to send correction, temp-correction and transform at the same time.
Change is fully tested, anyway I pulled to beta branch.

### CODE REVIEW

**Comment by brindosch** [comment]
very very good. Thank you for the fast reaction!

**Comment by AEtHeLsYn** [comment]
@brindosch 
;)

**Comment by brindosch** [comment]
@AEtHeLsYn 
Bad compile news :(
http://pastebin.com/ncsntr8q

**Comment by AEtHeLsYn** [comment]
I have those compile warnings always too, nothing to care about. To be sure that everything worked fine I downloaded the master branch and applied my fix, everything is ok.

**Comment by brindosch** [comment]
@AEtHeLsYn 
TPmodding tried again and it is working. (my crosscompile seems damaged)
I used his builds to test with HyperCon.
GREAT!

Thank you for everything :)

**Comment by AEtHeLsYn** [comment]
@brindosch 
After a couple problems with crosscompiling I recently bought a RPi3 ;)
BTW, I will be glad to help with anything here, I love hyperion and I kinda have programming skills ;)

**Comment by brindosch** [comment]
We "need" a crosscompile to 1click build new images for all platforms.

**Comment by AEtHeLsYn** [comment]
Yes, I'm aware of that. Noto a big fan of crosscompiling, but we need it here.

**Comment by brindosch** [comment]
Greetings @AEtHeLsYn 
The people love your color correction! (me too :)) But sad we found a problem that it looks like the temperature values are not read from the config.json
Could yu have a look? I also uploaded a ready to use hypercon with .dat and .json and the hyperion-remote log.
You could use a white picture you will see there is a big difference if you use hyperion -remote to send the values or not.
https://onedrive.live.com/redir?resid=7236025C06E3C265!3210&authkey=!AGPlhn9pCerdp-Y&ithint=file%2czip

Thank you for your feedback

**Comment by brindosch** [comment]
@AEtHeLsYn 
One additional question. How should you lower the brightness of your leds, if your leds are too bright for your taste (for example at the evening)
Thank you :)

**Comment by Paulchen-Panther** [comment]
@brindosch 
Der JSON wert in Hyperion [Zeile 111](https://github.com/hyperion-project/hyperion/blob/master/libsrc/hyperion/Hyperion.cpp#L111) stimmt nicht mit dem Wert in Hypercon [Zeile 125](https://github.com/hyperion-project/hypercon/blob/master/ConfigTool/src/org/hyperion/hypercon/spec/TransformConfig.java#L125) überein.
Das dürfte dein Problem mit der Farbtemperatur lösen.

Paulchen

**Comment by brindosch** [comment]
Tatsächlich, ich habe mich streng an die "Vorgabe" gehalten und nicht am Code orientiert, die Beispiel-Konfiguration spricht von temperature values. Mein Fehler, danke!

**Comment by brindosch** [comment]
@Paulchen-Panther 
At the initial commit there was correctionValue and a temperatureValue
https://github.com/hyperion-project/hyperion/pull/534/files
I see no deleted content here. So both should be grabbed from the config file.

**Comment by Paulchen-Panther** [comment]
https://github.com/hyperion-project/hyperion/blob/master/libsrc/hyperion/Hyperion.cpp#L862

**Comment by AEtHeLsYn** [comment]
@brindosch 
As already pointed by @Paulchen-Panther, I made a mistake uploading the correct config file, instead of "temperatureValues" the config file should have "correctionValues" below temperature section. 
In case you wonder why that happened, I am reusing the same function as color correction instead of creating another one with the same code.

**Pull request merged**
