### PR TITLE
init scripts need to send SIGTERM not SIGHUP

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Change the init scripts to send SIGTERM instead of SIGHUP
Removed the now unnnecessary set the leds to black
This allows hyperiond to switch the LEDs and exit cleanly.

Also a minor change to pgrep to exactly match on the hyperiond executable

**2.** If this changes affect the .conf file. Please provide the changed section
nope

**3.** Reference a issue (optional)
#575

### CODE REVIEW

**Comment by brindosch** [comment]
Did you tested both on a system?
Systemd was working for ma already with SPI, pwm not?

**Comment by penfold42** [comment]
Only Hyperion.init.sh on OSMC.

-HUP is clearly wrong. It's not caught by Hyperiond and it dies immediately

**Comment by penfold42** [comment]
On closer looking the systemd does NOT need fixing.
It refers to a reload option that hyperiond doesn't support

Lemme fix it before you merge

**Comment by penfold42** [comment]
done!
btw, systemd was working for you because systemd defaults to sending a SIGTERM

**Comment by brindosch** [comment]
Don´t get me wrong, we just want to ensure that we don´t screw up anything :+1: 
Thank you

**Comment by penfold42** [comment]
Testing ? What's that ?

**Pull request merged**
