### PR TITLE
AtmoOrb device support

### PR DESCRIPTION
**Pull request by RickDB**
**1.** Tell us something about your changes.

This adds support for the AtmoOrb device, it uses a simple network protocol and sends it data over UDP multicast to control Hue like lights.

However they offer much better performance with on average 1ms color changes depending on WiFi quality and can be controlled without the need of a bridge or additional IP configuration / pairing.
More detailed explanation and build instructions are in this topic:

http://forum.team-mediaportal.com/threads/diy-atmoorb-a-hue-like-mood-lamp-based-on-particle-photon-with-neopixel-tutorial-added.131901/

Can also be daisy chained to led strips besides the Orb and so long as FastLED supports them it will work.
Will update the demo videos soon as Hyperion smoothing works very nice with and shows smooth and fast transitions.

**2.** If these changes affect the .conf file. Please provide the changed section

A few settings had to be added and here are the list of changes:

- "port"     : 49692, <-- UDP port to send data over.
- "numLeds"     : 24, <-- number of leds per Orb, used to determine byte array size.
- "orbIds"   : [1],  <-- Unique Orb IDs to control (comma separated list), same PhilipsHue which is called lightids there.
- "switchOffOnBlack"     : true, <-- Identical to PhilipsHue, kept it in for later use.

Also there's a sample config here which uses 1 Orb: https://gist.github.com/RickDB/dfbb39c16a556ffe591b

In the Leds area the index is used as follows:

Index 0 = Orb ID 1
Index 1 = Orb ID 2
..and so forth.

So you can define several Orb IDs in the orbIds setting from above and in the Leds area you can define which scan area it utilizes.
You can have Orbs with the same ID so this only required for multiple Orb setups where you need different scan areas, couldn't find a nicer way of handling this yet.

**3.** Comments

Not a native C++ developer (C# mostly) so used the PhilipsHue device as a template and went from there, kept the code small and simple with inline documentation.

Tested to work with multiple Orbs already and it has a small user base which is one of the reasons I would like to add it to Hyperion, since building a Orb is fairly easy / low cost and compared to Hue much faster I'm hoping some will find it useful :)

### CODE REVIEW

**Comment by tpmodding** [comment]
Hey @RickDB nice to see you her! I know AtmoOrb :)

Just a few questions:
1. did you precompiled and tested it with your setup?
2. We have an "UDP-Device" doesnt it work with that?

**Comment by RickDB** [comment]
Hi @tpmodding,

Good to hear we have at some other Orb users out there :)

1. Manually compiled on a RPi2 using current master branch, didn't use precompiled builds and no errors / warnings during compile.
Can't test on other devices like beagle board but since I mostly kept to the included QT libraries it should be fine but of course would be great if someone can test it out on those as well to make sure.

2. Checked that one out but seemed better to keep this seperate as this uses UDP multicast and not direct IP 

Still new to Hyperion code so finding my way around it still, please let me know if something can be improved is :+1: 
Did just switch to CLion as Visual Studio was just messing up formatting, cleaned it up with that and formatting / indenting should now be fine.

**Comment by brindosch** [comment]
@tpmodding 
We should really earn some bucks for this ^^
@RickDB 
Well, i will implement your new device into Hypercon
regarding orb ids  you mean this formatting right?
`"orbIds" : [1,2,3,4], `
Additional it would be good if you could write a "AtmoOrb device" wiki aricle, wich explains the values in the config and maybe a short explanation of the AtmoOrb and a link to the DIY topic.
Thank you for your contribution!

**Comment by RickDB** [comment]
@brindosch Thanks for adding it to HyperCon:+1: 

The orbIds formatting example is correct, it's the same as with the PhilipsHue device only named differently.
Will write up a wiki page for it this week, the more documentation the better :)

**Comment by RickDB** [comment]
Btw forgot to ask, would it be possible to use a default value for the "output" setting in HyperCon when selecting AtmoOrb?

Since the multicast address will in most cases be the same for everyone it would be nice if it got filled in already like we do with AtmoLight.
It's this setting where the default value would be 239.15.18.2:

https://gist.github.com/RickDB/dfbb39c16a556ffe591b#file-atmoorb_sample_config-json-L21

**Comment by brindosch** [comment]
Yes, all values for your .conf are the default ones

**Comment by RickDB** [comment]
Awesome, thanks!

**Comment by brindosch** [comment]
@RickDB 
Do you need more than one id in one config?
I have problems to append []
HyperCon device construction is a simple "for" loop, that adds formatting depending on data type (string/int/bool)
Best i could add is "1,2,3,4,5,6" as string

**Comment by RickDB** [comment]
Yeah, because for multi-zone configs (left /right from tv) multiple ids are required.
"1,2,3,4,5,6" as string is fine, once HyperCon has that will adapt the atmoorb settings code to support it :)

**Comment by brindosch** [comment]
We are ready when you are :)
unbenannt
I have to fix the scroll behaviour later
```
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "atmoorb",
		"port"     : 49691,
		"output"     : "239.15.18.2",
		"transitiontime"     : 1,
		"numLeds"     : 24,
		"orbIds"     : "1",
		"switchOffOnBlack"     : true,
		"colorOrder" : "rgb"
	},
```
Well, the formatting is a mess, have a look later on this.

**Comment by RickDB** [comment]
Looks great :+1: 
Only the port in those examples is off by 1, should say 49692 :)

Did a test run with single and multiple zones and everything works as expected with the new settings layout so think it's ready for merge.
Created the Wiki page for it with examples and settings explanation:

https://github.com/tvdzwan/hyperion/wiki/AtmoOrb-device

**Comment by brindosch** [comment]
Ups, changed
Great!

**Pull request merged**
