### PR TITLE
Revert "Reads hue light ids in case the user did not supply any."

### PR DESCRIPTION
**Pull request by brindosch**
Reverts tvdzwan/hyperion#538

Please note the following compile error
http://pastebin.com/T8exijxS

### CODE REVIEW

**Comment by redPanther** [comment]
it seems the
#include <stdexcept>
is missing (needed by std::runtime_error). on some linux systems stdexcept is added automaticly. (e.g. on mine)
Try to add it in libsrc/leddevice/LedDevicePhilipsHue.cpp

**Comment by brindosch** [comment]
I am not very familiar with cpp´s
A include is easy, but i don´t know what exatly.

#include <exception>
?

**Comment by brindosch** [comment]
running smooth. Thank you :)
Are you sure you won´t join? ;)
https://github.com/hyperion-team

**Comment by redPanther** [comment]
Are you sure you won´t join? ;)
You have to invite me.

**Pull request closed without merging**
