### PR TITLE
Prio cleanup

### PR DESCRIPTION
**Pull request by redPanther**
This is a PR for issue  #532
The goal is to cleanup all priority values and make all prios settable via hyperion.config or command line (for external grabbers). This is neccessary for better predictable and understandable behaviour in more complex setups (especially in multi daemon setups).

list of changes:
- add external grabbers for osx and framebuffer (now all grabbers are available as standalone version)
- make QT5 work
- fix lineendings of some cmakelists.txt
- fix code layout of changed files to look like the rest of hyperion code
- preparation for refactoring of grabbers
 (grabbers especially the wrapper looks nearly the same for all grabbers. This should be refactored to minimizecode duplication)

In conclusion this task was a continuation of my prior work on proto/json forwarder.

**At this point I have to say a word to my OSX changes: this changes aren't tested!!!! I have no OSX and I "blind coded" the stuff. OSX people I need your help - please report if it's working or not.**

here is a table of the prio settings before my commits:
```
source           | intern | extern | Default prio | how to set           | source code
=================|========|========|==============|======================|===================================================
v4l              |   x    |        |      800     | hyperion.config.json | src/hyperiond/hyperiond.cpp
v4l              |        |    x   |      800     | command line         | src/hyperion-v4l2/hyperion-v4l2.cpp
amlogic          |   x    |        |      999     | not implemented      | libsrc/grabber/amlogic/AmlogicWrapper.cpp
amlogic          |        |    x   |      800     | command line         | src/hyperion-aml/hyperion-aml.cpp
dispmanx         |   x    |        |     1000     | not implemented      | libsrc/grabber/dispmanx/DispmanxWrapper.cpp
dispmanx         |        |    x   |      800     | command line         | src/hyperion-dispmanx/hyperion-dispmanx.cpp
x11              |   x    |        |              | not implemented      | not implemented
x11              |        |    x   |      800     | command line         | src/hyperion-x11/hyperion-x11.cpp
framebuffer      |   x    |        |     1000     | not implemented      | libsrc/grabber/framebuffer/FramebufferWrapper.cpp
framebuffer      |        |    x   |              | not implemented      | not implemented
osx              |   x    |        |     1000     | not implemented      | libsrc/grabber/osx/OsxWrapper.cpp
osx              |        |    x   |              | not implemented      | not implemented
bootsequence     |   x    |        |        0     | hyperion.config.json | src/hyperiond/hyperiond.cpp
Json (effects)   |        |    x   |      100     | command line         | src/hyperion-remote/hyperion-remote.cpp
Proto (grabbers) |        |    x   |              | def. by ext. source  | 
boblight         |   x    |        |      255     | not implemented      | libsrc/boblightserver/BoblightClientConnection.cpp
```

and this is the situation after my changes:
```
source           | intern | extern | Default prio | how to set           | source code
=================|========|========|==============|======================|===================================================
v4l              |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
v4l              |        |    x   |      800     | command line         | src/hyperion-v4l2/hyperion-v4l2.cpp
amlogic          |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
amlogic          |        |    x   |      800     | command line         | src/hyperion-aml/hyperion-aml.cpp
dispmanx         |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
dispmanx         |        |    x   |      800     | command line         | src/hyperion-dispmanx/hyperion-dispmanx.cpp
x11              |   x    |        |              | not implemented      | not implemented
x11              |        |    x   |      800     | command line         | src/hyperion-x11/hyperion-x11.cpp
framebuffer      |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
framebuffer      |        |    x   |      800     | command line         | src/hyperion-framebuffer/hyperion-framebuffer.cpp
osx              |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
osx              |        |    x   |      800     | command line         | src/hyperion-osx/hyperion-osx.cpp
bootsequence     |   x    |        |      990     | hyperion.config.json | src/hyperiond/hyperiond.cpp
Json (effects)   |        |    x   |      100     | command line         | src/hyperion-remote/hyperion-remote.cpp
Proto (grabbers) |        |    x   |              | def. by ext. source  | 
boblight         |   x    |        |      900     | hyperion.config.json | src/hyperiond/hyperiond.cpp
```

The idea is, that external sources overrules the internal sources. (default behaviour)
example: internal prio 900, external prio 800. if external source sends data, this would be displayed instead of the internal one. ( "the lower the number, the higher the priority" )

### CODE REVIEW

**Comment by tpmodding** [comment]
I have OSX @redPanther, i can test it later :)

**Comment by redPanther** [comment]
cool thx. Then you will be able to grab the screen via hyperion-osx grabber and send your data to your "raspi hyperion" ... No need to use full featured hyperiond on osx! cool isn't it?

**Comment by brindosch** [comment]
Thank you for your contribution!
You are a never stopping coding machine? :)

@tpmodding 
You never sad that, then we could build osx builds too! (was a feature request, too)

**Comment by brindosch** [comment]
@redPanther 
Just one quick question. What does the priority @ v4l2 section, if this is just triggered from command line?

**Comment by redPanther** [comment]
when using an external grabber e.g. hyperion-v4l2 the whole config isn't used! you have to configure all params on command line. There you can set (and thats not new) the prio. If you not set the prio you get the default value.

For usage of internal grabbers, the prio is configured via hyperion.config. If there is no value the default value is set.

**Comment by brindosch** [comment]
So i should disable (greyed out)  the value in HyperCon with a "hardcoded" tooltip? We shouldn´t promote what is not the case :)

**Comment by brindosch** [comment]
Oh just on thing: Could you integrate a version string for Hyperion that is visible in the log at startup.
I just have to know where it is to push the number, that people can report their version! It is a mess that no one could tell us the version he use!

**Comment by brindosch** [comment]
Also i could use this version in HyperCon! Lets say we are on V1.00.0 now. If we merge a new feature we could push to V1.01.0 and so on.
 When a new feature arrives, most we have to extend HyperCon so i will push it to V1.01.0 too.
If it is just a small bugix that need no change at Hypercon we could push to V1.01.1

Some thoughts about this?

**Comment by redPanther** [comment]
perhaps there is a misunderstanding? when using hypercon you configure always the internal stuff, also the v4l grabber. The prio should be settable!
I look into your hypercon - v4l2 is not external, this should be selectable like the led devices.

**Comment by brindosch** [comment]
Oh i´m sorry. Yes i thought that the external is the external.
Just to be sure. Now it is possible to set the "internal" frame grabber priority (depending on platform)

**Comment by brindosch** [comment]
this one
`	"framegrabber" : 
	{
		"width" : 80,
		"height" : 45,
		"frequency_Hz" : 10.0,
		"priority" : 900
	},`

**Comment by brindosch** [comment]
the longer i thought about versioning. to signalise the user how old the build is he uses. We should also add the compile date above/under/beneath the version. in dd.mm.yyyy
:)

**Comment by redPanther** [comment]
the config for "framegrabber" depends on how you compiled the source. This can be the "osx" framebuffer or dispmanx (broadcom videocore) grabber. 
In addition to that hyperiond includes 2 other grabbers: "grabber-v4l2" and "amlgrabber"

you can enable all tree together ([osx|framebuffer|dispmanx] [v4l2] [aml] ) but this make no sense, because you can't switch between those grabbers and you will always see the grabber with the lowest prio value.

I suggest for hypercon: make a selection between
- screen (section framebuffer)
- video source (section v4ls-grabber)
- wetek/amlogic (I think this is mainly the wetek stuff?) (section amlogic )

and then display all grabber specific options according to that seölected grabber

**Comment by brindosch** [comment]
@redPanther It is a little bit embarrassing now for me 
`"framegrabber" : { "width" : 80, "height" : 45, "frequency_Hz" : 10.0, "priority" : 900 },`
Yes possible/ No not possible

Thank you very much for the very good explanation

**Comment by redPanther** [comment]
Possible and usefull

**Comment by brindosch** [comment]
I´m sorry, a look at the commit and everything was explained -.-

Added Boblight priority
Added framegrabber priority

**Comment by redPanther** [comment]
@tpmodding any news from osx?

**Comment by tpmodding** [comment]
@redPanther 
CMake Error at cmake/qt4/FindPackageHandleStandardArgs.cmake:97 (message):
  Could NOT find Qt4 (missing: QT_QMAKE_EXECUTABLE QT_MOC_EXECUTABLE
  QT_RCC_EXECUTABLE QT_INCLUDE_DIR QT_LIBRARY_DIR QT_QTCORE_INCLUDE_DIR
  QT_QTCORE_LIBRARY QT_QTNETWORK_INCLUDE_DIR QT_QTNETWORK_LIBRARY
  QT_QTGUI_INCLUDE_DIR QT_QTGUI_LIBRARY QT_UIC_EXECUTABLE)
Call Stack (most recent call first):
  cmake/qt4/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
  cmake/qt4/FindQt4.cmake:1223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:105 (find_package)

**Comment by tpmodding** [comment]
port doesnt work, used brew for mac :)
it works!!!! i start hyperiond and after that i have to start hyperion-osx and it works very good!! :)

**Comment by redPanther** [comment]
@tpmodding thx for testing and the fix :-)

**Comment by redPanther** [comment]
.... since

**Comment by brindosch** [comment]
Yes, we will merge 3 of 4 commits :)

**Comment by brindosch** [comment]
sorry @redPanther, i have to setting up a 24/7 connection to tpmodding to prevent this spam :)
@tpmodding 
Debian 8 use gcc 4.9.x 
Debian 7 use gcc 4.7.x
Ubuntu 14.04 use gcc 4.8.4 

For the 32/64bit bins we should not go higher than gcc 4.8 for compile

You get the version info with
gcc -v

Now RPi.
Raspbian wheezy users complain to update their gcc too. I build my bins with jessie
Based on the post at the rpiforum
Raspbian wheezy use gcc 4.6.x
Raspbian jessie use gcc 4.8.x

We should stick with the wheezy source as long the people using it (maybe one year? or two)
I get my source from a raspian wheezy for crosscompile. i don´t know if this matters here!!!

And don´t merge the color correction, HyperCon is not ready for this at the moment :) All other seems ok

**Comment by brindosch** [comment]
@redPanther 
Now i screwed it up :/

**Comment by penfold42** [comment]
Just been testing this.
With these defaults, its seems the startup effect get over-ridden almost immediately by the frame grabber.
Looking at the logic above this does seem to be expected behaviour, but not what "I" would have expected!

Shouldn't the startup effect priority be almost zero given its not going to run for very long?

Am i missing something?

thanks!

**Comment by redPanther** [comment]
Problem is that you can set the time to 0. This means infinity. Then no one had a chance to overrule the effect. We discused it in the static color issue. 

Will think about it later today.

**Comment by penfold42** [comment]
maybe print a warning ? 
Maybe special case the 0 ?
Maybe just document it. 

As best I can tell right now, the defaults won't work well for anyone with a grabber defined.

Or maybe it's because I have grab menu enabled too *grin*

**Comment by redPanther** [comment]
perhaps this:
if boot duration 0 then do it as now otherwise set prio to 0 until boot duration ends

**Pull request merged**
