### PR TITLE
Orange pi support

### PR DESCRIPTION
**Pull request by komw**
Orange pi support documentation, added build.sh for easy prepare a environment for compiling

### CODE REVIEW

**Comment by tpmodding** [comment]
there is an conflict?

**Comment by komw** [comment]
OK, I resolve it, and then opern a pul request

**Comment by brindosch** [comment]
Hello @komw ,
you want to add the following line
`+cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=ON ..`
This line is already in the HowTo
```
# or if you are not compiling on the raspberry pi and need to disable the Dispmanx grabber and support for spi devices
cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=ON 
```
You could add the orange pi to the description
Thank you for your build.sh. But we can´t add. We are using just a generic .sh

**Comment by komw** [comment]
Conflicts resolved, build.sh deleted, added description for orange pi

**Comment by brindosch** [comment]
Added, thank you

**Pull request closed without merging**
