### PR TITLE
Replace XGetImage with XShmGetImage

### PR DESCRIPTION
**Pull request by Paulchen-Panther**

### CODE REVIEW

**Comment by oCanna** [comment]
Hello,

very nice commits.

But I wasn't able to compile with ur changes included because of some missing includes.
In addition I also found out that the cpu usage (the xorg process mainly) was pretty high.

So I made a patch that hopefully improves things a little bit.
```
diff --git a/include/grabber/X11Grabber.h b/include/grabber/X11Grabber.h
--- a/include/grabber/X11Grabber.h
+++ b/include/grabber/X11Grabber.h
@@ -6,6 +6,10 @@
 
 // X11 includes
 #include <X11/Xlib.h>
+#include <X11/extensions/XShm.h>
+
+#include <sys/ipc.h>
+#include <sys/shm.h>
 
 class X11Grabber
 {
@@ -14,8 +18,8 @@ public:
     X11Grabber(int cropLeft, int cropRight, int cropTop, int cropBottom, int horizontalPixelDecimation, int verticalPixelDecimation);
 
 	virtual ~X11Grabber();
-
-	int open();
+	
+	bool Setup();
 
 	Image<ColorRgb> & grab();
 
@@ -27,18 +31,23 @@ private:
     int _cropTop;
     int _cropBottom;
     
-    Screen *Xscreen;
-    XImage *xImage;
-    XShmSegmentInfo shminfo;
-    int screen;
+	XImage* _xImage;	
+	XShmSegmentInfo _shminfo;
 
 	/// Reference to the X11 display (nullptr if not opened)
-	Display * _x11Display;
+	Display* _x11Display;
+	Window _window;
+	XWindowAttributes _windowAttr;
 
 	unsigned _screenWidth;
 	unsigned _screenHeight;
+	unsigned _croppedWidth;
+	unsigned _croppedHeight;
 
 	Image<ColorRgb> _image;
-
+		
+	void freeResources();
+	void setupResources();
+	
 	int updateScreenDimensions();
 };
diff --git a/libsrc/grabber/x11/X11Grabber.cpp b/libsrc/grabber/x11/X11Grabber.cpp
--- a/libsrc/grabber/x11/X11Grabber.cpp
+++ b/libsrc/grabber/x11/X11Grabber.cpp
@@ -17,98 +17,116 @@ X11Grabber::X11Grabber(int cropLeft, int cropRight, int cropTop, int cropBottom,
     _x11Display(nullptr),
     _screenWidth(0),
     _screenHeight(0),
+	_croppedWidth(0),
+	_croppedHeight(0),
     _image(0,0)
 {
     _imageResampler.setHorizontalPixelDecimation(horizontalPixelDecimation);
     _imageResampler.setVerticalPixelDecimation(verticalPixelDecimation);
-    _imageResampler.setCropping(0, 0, 0, 0); // cropping is performed by XGetImage
+    _imageResampler.setCropping(0, 0, 0, 0); // cropping is performed by XShmGetImage
 }
 
 X11Grabber::~X11Grabber()
 {
     if (_x11Display != nullptr)
     {
+		freeResources();
         XCloseDisplay(_x11Display);
     }
 }
 
-int X11Grabber::open()
+void X11Grabber::freeResources()
 {
-    const char * display_name = nullptr;
-    _x11Display = XOpenDisplay(display_name);
+    // Cleanup allocated resources of the X11 grab
+    XShmDetach(_x11Display, &_shminfo);
+    XDestroyImage(_xImage);
+    shmdt(_shminfo.shmaddr);
+    shmctl(_shminfo.shmid, IPC_RMID, 0);	
+};
+
+void X11Grabber::setupResources(){
+    _xImage = XShmCreateImage(_x11Display, _windowAttr.visual,
+				 _windowAttr.depth, ZPixmap, NULL, &_shminfo,
+				 _croppedWidth, _croppedHeight);
+    
+    _shminfo.shmid = shmget(IPC_PRIVATE, _xImage->bytes_per_line * _xImage->height, IPC_CREAT|0777);
+    _shminfo.shmaddr = _xImage->data = (char*)shmat(_shminfo.shmid,0,0);
+    _shminfo.readOnly = False;
+    
+    XShmAttach(_x11Display, &_shminfo);	
+};
 
+bool X11Grabber::Setup()
+{
+    _x11Display = XOpenDisplay(NULL);
     if (_x11Display == nullptr)
     {
-        std::cerr << "Failed to open the default X11-display" << std::endl;
-        return -1;
+		std::cerr << "Unable to open display";
+		if (getenv("DISPLAY"))
+			std::cerr <<  " " << std::string(getenv("DISPLAY")) << std::endl;
+		else
+			std::cerr << ". DISPLAY environment variable not set" << std::endl;
+        return false;
     }
+	
+	_window = DefaultRootWindow(_x11Display);
 
-    return 0;
+    return true;
 }
 
 Image<ColorRgb> & X11Grabber::grab()
 {
-    if (_x11Display == nullptr)
-    {
-        open();
-    }
-
     updateScreenDimensions();
-    
-    Xscreen = DefaultScreenOfDisplay(_x11Display);
-
-    const unsigned croppedWidth  = _screenWidth - _cropLeft - _cropRight;
-    const unsigned croppedHeight = _screenHeight - _cropTop - _cropBottom;
-    
-    xImage = XShmCreateImage(_x11Display,   DefaultVisualOfScreen(Xscreen),
-				  DefaultDepthOfScreen(Xscreen),
-				  ZPixmap, NULL, &shminfo,
-				  croppedWidth, croppedHeight);
-    
-    shminfo.shmid = shmget(IPC_PRIVATE, xImage->bytes_per_line * xImage->height, IPC_CREAT|0777);
-    shminfo.shmaddr = xImage->data = (char*)shmat(shminfo.shmid,0,0);
-    shminfo.readOnly = False;
-    
-    XShmAttach(_x11Display, &shminfo);
 
     // Capture the current screen
-    XShmGetImage(_x11Display, DefaultRootWindow(_x11Display), xImage, _cropLeft, _cropTop, 0x00FFFFFF);
-    if (xImage == nullptr)
+    XShmGetImage(_x11Display, _window, _xImage, _cropLeft, _cropTop, 0x00FFFFFF);
+    if (_xImage == nullptr)
     {
         std::cerr << "Grab failed" << std::endl;
         return _image;
     }
 
-    _imageResampler.processImage(reinterpret_cast<const uint8_t *>(xImage->data), xImage->width, xImage->height, xImage->bytes_per_line, PIXELFORMAT_BGR32, _image);
-
-    // Cleanup allocated resources of the X11 grab
-    XShmDetach(_x11Display, &shminfo);
-    XDestroyImage(xImage);
-    shmdt (shminfo.shmaddr);
-    shmctl(shminfo.shmid, IPC_RMID, 0);
+    _imageResampler.processImage(reinterpret_cast<const uint8_t *>(_xImage->data), _xImage->width, _xImage->height, _xImage->bytes_per_line, PIXELFORMAT_BGR32, _image);
 
     return _image;
 }
 
 int X11Grabber::updateScreenDimensions()
 {
-    XWindowAttributes window_attributes_return;
-    const Status status = XGetWindowAttributes(_x11Display, DefaultRootWindow(_x11Display), &window_attributes_return);
+	const Status status = XGetWindowAttributes(_x11Display, _window, &_windowAttr);
     if (status == 0)
     {
         std::cerr << "Failed to obtain window attributes" << std::endl;
         return -1;
     }
 
-    if (_screenWidth == unsigned(window_attributes_return.width) && _screenHeight == unsigned(window_attributes_return.height))
+    if (_screenWidth == unsigned(_windowAttr.width) && _screenHeight == unsigned(_windowAttr.height))
     {
         // No update required
         return 0;
     }
+
     std::cout << "Update of screen resolution: [" << _screenWidth << "x" << _screenHeight <<"] => ";
-    _screenWidth  = window_attributes_return.width;
-    _screenHeight = window_attributes_return.height;
+	
+	if (_screenWidth || _screenHeight)
+		freeResources();
+	
+	_screenWidth  = _windowAttr.width;
+	_screenHeight = _windowAttr.height;
+	
     std::cout << "[" << _screenWidth << "x" << _screenHeight <<"]" << std::endl;
+	
+	if (_screenWidth > unsigned(_cropLeft + _cropRight))
+		_croppedWidth  = _screenWidth - _cropLeft - _cropRight;
+	else
+		_croppedWidth  = _screenWidth;
+	
+	if (_screenHeight > unsigned(_cropTop + _cropBottom))
+		_croppedHeight = _screenHeight - _cropTop - _cropBottom;
+	else
+		_croppedHeight = _screenHeight;
+	
+	setupResources();
 
     return 0;
 }
diff --git a/src/hyperion-x11/X11Wrapper.cpp b/src/hyperion-x11/X11Wrapper.cpp
--- a/src/hyperion-x11/X11Wrapper.cpp
+++ b/src/hyperion-x11/X11Wrapper.cpp
@@ -29,6 +29,11 @@ void X11Wrapper::stop()
     _timer.stop();
 }
 
+bool X11Wrapper::displayInit()
+{
+    return _grabber.Setup();
+}
+
 void X11Wrapper::capture()
 {
     const Image<ColorRgb> & screenshot = _grabber.grab();
diff --git a/src/hyperion-x11/X11Wrapper.h b/src/hyperion-x11/X11Wrapper.h
--- a/src/hyperion-x11/X11Wrapper.h
+++ b/src/hyperion-x11/X11Wrapper.h
@@ -19,6 +19,8 @@ public:
     void start();
 
     void stop();
+	
+	bool displayInit();
 
 signals:
     void sig_screenshot(const Image<ColorRgb> & screenshot);
diff --git a/src/hyperion-x11/hyperion-x11.cpp b/src/hyperion-x11/hyperion-x11.cpp
--- a/src/hyperion-x11/hyperion-x11.cpp
+++ b/src/hyperion-x11/hyperion-x11.cpp
@@ -77,6 +77,9 @@ int main(int argc, char ** argv)
                     argCropBottom.getValue(),
                     argSizeDecimation.getValue(), // horizontal decimation
                     argSizeDecimation.getValue()); // vertical decimation
+					
+		if (!x11Wrapper.displayInit())
+			return -1;
 
         if (argScreenshot.isSet())
         {
```

**Comment by Paulchen-Panther** [comment]
Many Thanks oCanna.
Sorry for the missing includes. I have updated the Pull Request.

**Comment by pdf** [comment]
This is a good start, but I don't think you can just replace `XGetImage` entirely - you should only enable `XShmGetImage` if it's supported by the server, using `XShmQueryExtension()` to test.

Also, please rebase and remove the effects stuff from this PR (police).

**Comment by brindosch** [comment]
This pr was merged Jan 21, i would rather keep the effects :)

**Comment by pdf** [comment]
@brindosch I presume you're talking about the police effect?  A rebase should get it out of this PR if it's been merged.

**Pull request merged**
